### ISSUE TITLE
无法加载

### ISSUE THREAD

**Issue by lin6953** [ChenXu233/nonebot-plugin-summary#1]
![Image_1730901890218.png](https://github.com/user-attachments/assets/328f47f7-ccb2-410c-adda-6cb556a812d5)

**Comment by ChenXu233** [comment]
插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以

**Comment by lin6953** [comment]
> 插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以

token可以写key吗？sk-开头的

**Comment by ChenXu233** [comment]
> > 插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以
> 
> token可以写key吗？sk-开头的

可以，就是写key，然后还有endpoint需要填写，填写成你的模型访问的位置。

**Comment by lin6953** [comment]
> > > 插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以
> > 
> > token可以写key吗？sk-开头的
> 
> 可以，就是写key，然后还有endpoint需要填写，填写成你的模型访问的位置。

大佬请在README.md里写一下配置项，默认值，不然我估计会有挺多issues的

**Comment by ChenXu233** [comment]
> > > > 插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以
> > > 
> > > 
> > > token可以写key吗？sk-开头的
> > 
> > 
> > 可以，就是写key，然后还有endpoint需要填写，填写成你的模型访问的位置。
> 
> 大佬请在README.md里写一下配置项，默认值，不然我估计会有挺多issues的

也是有这个打算的本来，但是太忙了一直忘记

**Comment by lin6953** [comment]
> > > > > 插件需要调用AI，请在环境配置里面写入Token和AI访问位置，理论OpenAI格式都可以
> > > > 
> > > > 
> > > > token可以写key吗？sk-开头的
> > > 
> > > 
> > > 可以，就是写key，然后还有endpoint需要填写，填写成你的模型访问的位置。
> > 
> > 大佬请在README.md里写一下配置项，默认值，不然我估计会有挺多issues的
> 
> 也是有这个打算的本来，但是太忙了一直忘记

大佬抽空写一下吧，我不知道配置项有啥

**Comment by ChenXu233** [comment]
OK，写完了（
